package edu.byu.cs.adbcj.mysql;

public enum ClientCapabilities {
	LONG_PASSWORD,
	FOUND_ROWS,
	LONG_COLUMN_FLAG,
	CONNECT_WITH_DB,
	NO_SCHEMA,
	COMPRESS,
	ODBC_CLIENT,
	LOCAL_FILES,
	IGNORE_SPACES,
	PROTOCOL_4_1,
	INTERACTIVE,
	SSL,
	IGNORE_SIGPIPE,
	TRANSACTIONS,
	PROTOCOL_4_1_OLD,
	SECURE_AUTHENTICATION,
}
